services:
  db:
    image: "mysql"
    ports: 
            - "3306:3306"
    environment:
            - MYSQL_ROOT_PASSWORD=rahulrds
            - MYSQL_USER=rahul
            - MYSQL_PASSWORD=rahulrds
            - MYSQL_DATABASE=library
    volumes:
        - mysql-data-vol:/var/lib/mysql

volumes:
    mysql-data-vol:
        external: false

