# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI CD for React Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: slms_frontend

jobs:
  build-push-deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: | # log into docker hub account
        sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image # push The image to the docker hub
      run: sudo docker build . --file client/Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Docker Push
      run: sudo docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Delete running application
      #run: sudo docker rm -f $(sudo docker ps -a -q)
      run: sudo docker rm -f slms_f
    - name: Deploy to docker
      run: sudo docker run -d --name slms_f -p 8081:80 $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
